using System;
using System.Collections.Generic;
using System.Text;

namespace dh.Media.CMP.Data.Entity
{
    public class AudienceQuery:Helpers.Entity
    {
        public override int Id { get; set; }
        public int RetailClientId { get; set; }
        public int ClientId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int CreatedDate { get; set; }
        public DateTime UpdatedDate { get; set; }
        public int CreatedByUserId { get; set; }
        public int UpdatedByUserId { get; set; }
        public DateTime? ArchivedDate { get; set; }
        public int? ArchivedByUserId { get; set; }
        public RetailClient RetailClient { get; set; }
        public Client Client { get; set; }
        public Account CreatedBy { get; set; }
        public Account UpdatedBy { get; set; }
        public Account ArchivedBy { get; set; }
        public int IsAutoGenerated { get; set; }
        public long? Reach { get; set; }
        public int Status { get; set; }
        public virtual ICollection<AudienceCriterion> AudienceCriterion { get; set; }
        public virtual ICollection<AudienceObjective> AudienceObjectives { get; set; }
    }
}
